# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "66739d2a8736f1300918f17da4844b53"
application_url = "https://d23vj80oas4fdj.cloudfront.net/"
embedded = true
name = "custom-app-lambda-dynamodb"
handle = "custom-app-lambda-dynamodb"

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://d23vj80oas4fdj.cloudfront.net/api/auth" ]

[pos]
embedded = false
